모든 2, 4, 6과 dist를 구해서 dist가 threshold 이하면 무조건 2, 4, 6으로 취급하기로 했을 때
못찾은 6 2개를 찾을 수 있을지?


In [1]:
%load_ext lab_black
%cd ../../..

/home/shim/cev/dl/log-analytics


In [2]:
import torch
import numpy as np
import pandas as pd

In [3]:
deck1 = torch.load("results/distilbert-base-uncased-ver7/distilbert-base-uncased-focal-AdamW-lr1e-05-ver7-os10_3-deck1.pth")
deck2 = torch.load("results/distilbert-base-uncased-ver7/distilbert-base-uncased-focal-AdamW-lr1e-05-ver7-os10_3-deck2.pth")

In [62]:
sdf = pd.read_csv("data/ori/test.csv")

In [5]:
deck1["feat_"] = deck1["feat"].cuda()
deck2["feat_"] = deck2["feat"].cuda()

In [6]:
deck1.keys(), deck2.keys()

(dict_keys(['feat', 'otext', 'tlevel', 'fclevel', 'feat_']),
 dict_keys(['feat', 'otext', 'fclevel', 'ids', 'feat_']))

In [25]:
(deck1["tlevel"] == 2).nonzero()[8]

tensor([336873])

In [32]:
(deck2["fclevel"] == 2).nonzero()[0]

tensor([12957])

In [55]:
deck1["otext"][219277]

'useradd: new group: name=test, GID=1001'

In [69]:
deck2["otext"][(deck2["fclevel"] == 6).nonzero()[0]]

"sshd: Bad protocol version identification '\\003' from 185.176.220.106 port 65322"

In [38]:
feat_lv2_ = deck1["feat_"][(deck1["tlevel"] == 2).nonzero()][:, 0, :]
feat_lv4_ = deck1["feat_"][(deck1["tlevel"] == 4).nonzero()][:, 0, :]
feat_lv6_ = deck1["feat_"][(deck1["tlevel"] == 6).nonzero()][:, 0, :]

In [39]:
feat2_lv2_ = deck2["feat_"][(deck2["fclevel"] == 2).nonzero()][:, 0, :]
feat2_lv4_ = deck2["feat_"][(deck2["fclevel"] == 4).nonzero()][:, 0, :]
feat2_lv6_ = deck2["feat_"][(deck2["fclevel"] == 6).nonzero()][:, 0, :]

In [56]:
dists, indices = torch.norm(feat_lv6_ - feat2_lv6_[1], p=None, dim=1).topk(1, largest=False)
dists, indices

(tensor([2.1685], device='cuda:0'), tensor([3], device='cuda:0'))

In [54]:
dists, indices = torch.norm(deck1["feat_"] - feat2_lv6_[1], p=None, dim=1).topk(1, largest=False)
dists, indices

(tensor([2.1685], device='cuda:0'), tensor([219277], device='cuda:0'))